import numpy as np
import matplotlib.pyplot as plt
import skimage
import OpticalSystems as optic
import Illumination as illum


class SimulatorSIM:
    def __init__(self):
        ...

    def convolve_with_psf(self, image): ...

    def generate_sim_images(self, sample): ...

    def add_poisson_noise(self, image): ...

    def add_gaussian_noise(self, image): ...

    def generate_true_wiener_filter(self, ssnr_calculator): ...

    def apply_filter(self, image, filter): ...
    
    def deconvolve(self): ...

class Simulator2DSIM(SimulatorSIM): ...

class Simulator3DSIM(SimulatorSIM): ...
